# pandas data frame

In [1]:
import pandas as pd

In [2]:
s=[0,1,2,3,4,5]

In [4]:
pd.DataFrame(s,columns=[" degiskenler" ])

degiskenler
0             0
1             1
2             2
3             3
4             4
5             5

In [7]:
# iki boyutlu

In [8]:
import numpy as np

In [10]:
ss=np.arange(1,10).reshape(3,3)
ss

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
pd.DataFrame(ss,columns=["aa","ss","dd"])

aa  ss  dd
0   1   2   3
1   4   5   6
2   7   8   9

In [13]:
#df isim degistirme

In [14]:
df=pd.DataFrame(ss,columns=["aa","ss","dd"])

In [16]:
df.head()

aa  ss  dd
0   1   2   3
1   4   5   6
2   7   8   9

In [17]:
df.columns

Index(['aa', 'ss', 'dd'], dtype='object')

In [18]:
df.columns=("qq","ww","ee")

In [19]:
df

qq  ww  ee
0   1   2   3
1   4   5   6
2   7   8   9

In [20]:
type(df)

pandas.core.frame.DataFrame

In [21]:
df.shape

(3, 3)

In [22]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['qq', 'ww', 'ee'], dtype='object')]

In [23]:
df.ndim

2

In [24]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
type(df.values)

numpy.ndarray

In [26]:
df.size

9

In [27]:
df.head(1)

qq  ww  ee
0   1   2   3

In [28]:
df.tail(1)

qq  ww  ee
2   7   8   9

In [29]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [30]:
pd.DataFrame(a,columns=["www"])

www
0    1
1    2
2    3