# alt kumede islemler

In [1]:
import numpy as np

In [5]:
a=np.random.randint(10,size=(5,5))

In [6]:
a

array([[7, 2, 5, 9, 1],
       [3, 9, 7, 2, 6],
       [3, 6, 0, 0, 4],
       [8, 6, 4, 5, 3],
       [9, 4, 0, 0, 6]])

In [7]:
alt_a=a[0:2,0:2]
alt_a

array([[7, 2],
       [3, 9]])

In [8]:
alt_a[0,0]=5555
alt_a[0,0]

5555

In [10]:
a

array([[5555,    2,    5,    9,    1],
       [   3,    9,    7,    2,    6],
       [   3,    6,    0,    0,    4],
       [   8,    6,    4,    5,    3],
       [   9,    4,    0,    0,    6]])

In [11]:
#yapilan islem ana kumede de gerceklesti, cozumu altta:

In [13]:
m=np.random.randint(10,size=(5,5))
m

array([[2, 9, 6, 3, 7],
       [3, 3, 2, 2, 6],
       [9, 4, 4, 1, 1],
       [5, 9, 6, 8, 3],
       [8, 0, 1, 4, 7]])

In [14]:
alt_m=m[0:2,0:2].copy()
alt_m

array([[2, 9],
       [3, 3]])

In [15]:
alt_m[0,0]=7777
alt_m[0,0]

7777

In [17]:
m
#ana kumede degisim olmadi

array([[2, 9, 6, 3, 7],
       [3, 3, 2, 2, 6],
       [9, 4, 4, 1, 1],
       [5, 9, 6, 8, 3],
       [8, 0, 1, 4, 7]])