In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4.5])

In [3]:
a

array([1. , 2. , 3. , 4.5])

In [5]:
np.array((a),dtype="int")

array([1, 2, 3, 4])

In [ ]:
# sifirdan array olusturmak

In [6]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.ones((3,3),dtype = float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.full((4,7),9,dtype = int)

array([[9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9]])

In [10]:
np.arange(1,30,4)

array([ 1,  5,  9, 13, 17, 21, 25, 29])

In [11]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
np.random.normal(10,4,(3,4))
#10=ortalama, 4= standart sapma

array([[15.90799531,  7.99284322, 13.26684301, 11.46053511],
       [ 3.77674214, 13.46279225, 11.92653157,  5.6564101 ],
       [ 4.8318967 ,  8.46591716,  3.971373  ,  8.4277865 ]])

In [14]:
np.random.randint(1,5,(3,3))

array([[2, 4, 2],
       [4, 4, 4],
       [1, 4, 1]])