# array birlestirme(concatenation)

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
b=np.array([4,5,6])

In [5]:
c= np.concatenate([a,b])

In [6]:
c

array([1, 2, 3, 4, 5, 6])

In [7]:
#iki boyut

In [14]:
aa=np.array([[1,2,3],[3,4,5]])

In [18]:
bb=np.concatenate([aa,aa])
bb

array([[1, 2, 3],
       [3, 4, 5],
       [1, 2, 3],
       [3, 4, 5]])

In [19]:
bb=np.concatenate([aa,aa],axis=0)
bb

array([[1, 2, 3],
       [3, 4, 5],
       [1, 2, 3],
       [3, 4, 5]])

In [20]:
bb=np.concatenate([aa,aa],axis=1)
bb

array([[1, 2, 3, 1, 2, 3],
       [3, 4, 5, 3, 4, 5]])