# array ayirma(splitting)

In [3]:
import numpy as np

In [4]:
x= np.array([1,2,3,99,99,3,2,1])

In [6]:
a,b,c=np.split(x,[3,5])
#3 uncu ve 5 inci elemana kadar ayir

In [7]:
a

array([1, 2, 3])

In [8]:
b

array([99, 99])

In [9]:
c

array([3, 2, 1])

In [10]:
# iki boyutta

In [ ]:
#yatay

In [23]:
y=np.arange(0,32,2).reshape(4,4)
y

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [24]:
ust,alt=np.vsplit(y,2)

In [25]:
ust

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14]])

In [26]:
alt

array([[16, 18, 20, 22],
       [24, 26, 28, 30]])

In [27]:
#dikey

In [28]:
y

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [29]:
sol,sag=np.hsplit(y,2)

In [30]:
sol

array([[ 0,  2],
       [ 8, 10],
       [16, 18],
       [24, 26]])

In [31]:
sag

array([[ 4,  6],
       [12, 14],
       [20, 22],
       [28, 30]])