# fancy index ile elemanlara erismek

In [1]:
import numpy as np

In [2]:
v=np.arange(0,31,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [3]:
kume=[1,3,5]

In [5]:
v[kume]

array([ 3,  9, 15])

In [6]:
#iki boyutta

In [7]:
m=np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [8]:
satir=np.array([0,1])
sutun=np.array([1,2])

In [9]:
m[satir,sutun]

array([1, 6])

In [10]:
#basit islem ile fancy

In [11]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
m[1,[1,2]]

array([5, 6])

In [14]:
#slice ile fancy

In [15]:
m[0:,[1,2]]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])