# index ile elemanlara erismek

In [1]:
import numpy as np

In [2]:
x=np.random.randint(10,size=10)

In [3]:
x

array([1, 1, 7, 4, 4, 2, 8, 3, 1, 9])

In [4]:
x[0]

1

In [5]:
x[7]

3

In [6]:
x[-2]

1

In [ ]:
#iki boyutlu

In [7]:
m=np.random.randint(15,size=(5,4))
m

array([[ 2,  2, 10, 13],
       [11, 10,  7,  3],
       [10,  4,  4,  8],
       [ 7,  2, 13,  4],
       [ 6,  5,  1, 12]])

In [8]:
m[2,0]

10

In [9]:
m[4,3]=120
m

array([[  2,   2,  10,  13],
       [ 11,  10,   7,   3],
       [ 10,   4,   4,   8],
       [  7,   2,  13,   4],
       [  6,   5,   1, 120]])

In [10]:
m[0][0]=5.3
m

array([[  5,   2,  10,  13],
       [ 11,  10,   7,   3],
       [ 10,   4,   4,   8],
       [  7,   2,  13,   4],
       [  6,   5,   1, 120]])

In [ ]:
#array int oldugu icin girilen float in kesirli kısmını attı