# kosullu eleman islemleri

In [1]:
import numpy as np

In [3]:
m=np.array([1,2,3,4,5])

In [4]:
m<3

array([ True,  True, False, False, False])

In [5]:
m[m<3]

array([1, 2])

In [6]:
m[m>=3]

array([3, 4, 5])

In [7]:
m[m!=3]

array([1, 2, 4, 5])

In [8]:
m**2

array([ 1,  4,  9, 16, 25])

In [9]:
m/3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])