# matematiksel islemler

In [2]:
import numpy as np

In [3]:
v=np.array([1,2,3,4,5])

In [4]:
v*2

array([ 2,  4,  6,  8, 10])

In [5]:
v-1

array([0, 1, 2, 3, 4])

In [6]:
v**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [11]:
# u func
v

array([1, 2, 3, 4, 5])

In [10]:
np.subtract(v,11)

array([-10,  -9,  -8,  -7,  -6])

In [12]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [13]:
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [14]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [16]:
np.absolute(np.array([-5]))

array([5])

In [17]:
np.cos(45)

0.5253219888177297

In [18]:
np.tan(30)

-6.405331196646276

In [19]:
np.log(v)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [21]:
np.log2(v)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

In [22]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\seyfu\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\seyfu\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>>

In [23]:
# ihtiyacın olan seyleri cheat sheet ile ara google da