# Reshape(yeniden boyutlandirma)

In [4]:
import numpy as np

In [15]:
a=np.arange(1,12,2)

In [16]:
a

array([ 1,  3,  5,  7,  9, 11])

In [19]:
a.reshape(2,3)

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [21]:
a.ndim

1

In [22]:
b=a.reshape(1,6)

In [23]:
b

array([[ 1,  3,  5,  7,  9, 11]])

In [26]:
b.ndim
#artik tek boyutlu matris(dizi degil)

2