# slicing (alt kume islemleri)

In [1]:
import numpy as np

In [3]:
x=np.arange(20,31)
x

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [4]:
x[0:5]

array([20, 21, 22, 23, 24])

In [5]:
x[0::2]
#ikiser olarak alir

array([20, 22, 24, 26, 28, 30])

In [6]:
x[1::2]

array([21, 23, 25, 27, 29])

In [ ]:
#iki boyutlu

In [8]:
m=np.random.randint(15,size=(6,6))
m

array([[13,  9, 14,  3, 13, 10],
       [12,  1,  8,  6,  3,  5],
       [10,  2,  5,  0, 12,  9],
       [12,  3,  3, 10,  6,  5],
       [ 0, 11, 12, 12, 10,  2],
       [ 2,  5, 14, 13,  8,  2]])

In [9]:
m[:,3]

array([ 3,  6,  0, 10, 12, 13])

In [10]:
m[:,0]

array([13, 12, 10, 12,  0,  2])

In [11]:
m[4,:]

array([ 0, 11, 12, 12, 10,  2])

In [12]:
m[0:2,0:3]

array([[13,  9, 14],
       [12,  1,  8]])

In [13]:
m[4:,0:5]

array([[ 0, 11, 12, 12, 10],
       [ 2,  5, 14, 13,  8]])

In [14]:
m[0:2,0:1]

array([[13],
       [12]])