# sorting(siralama)

In [2]:
import numpy as np

In [3]:
x=np.array([7,4,5,1,2,6,3])

In [4]:
np.sort(x)

array([1, 2, 3, 4, 5, 6, 7])

x.sort()

In [6]:
x

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#iki boyutlu dizilerde

In [7]:
y=np.random.normal(20,5,(4,4))

In [8]:
y

array([[23.64640743, 20.46872186, 17.25274632, 19.02326576],
       [20.22179046, 17.57726053, 20.67497809, 25.95827193],
       [27.03646266, 23.6827842 , 17.94456377, 22.21386266],
       [24.12648575, 24.13011307, 19.95017487, 19.1544898 ]])

In [9]:
np.sort(y,axis=0)

array([[20.22179046, 17.57726053, 17.25274632, 19.02326576],
       [23.64640743, 20.46872186, 17.94456377, 19.1544898 ],
       [24.12648575, 23.6827842 , 19.95017487, 22.21386266],
       [27.03646266, 24.13011307, 20.67497809, 25.95827193]])

In [10]:
np.sort(y,axis=1)

array([[17.25274632, 19.02326576, 20.46872186, 23.64640743],
       [17.57726053, 20.22179046, 20.67497809, 25.95827193],
       [17.94456377, 22.21386266, 23.6827842 , 27.03646266],
       [19.1544898 , 19.95017487, 24.12648575, 24.13011307]])